"""Add url field to community_uploads

Revision ID: 1739dfe43722
Revises: 4d59f4e2d122
Create Date: 2025-03-15 16:15:10.637879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1739dfe43722'
down_revision: Union[str, None] = '4d59f4e2d122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_uploads', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('community_uploads', 'url')
    # ### end Alembic commands ###
