"""Remove resource_id from bookmarks

Revision ID: 917a9d74c8b9
Revises: 320c844d2886
Create Date: 2025-03-14 19:57:37.550565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '917a9d74c8b9'
down_revision: Union[str, None] = '320c844d2886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookmarks', 'url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('bookmarks', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('bookmarks', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('bookmarks', 'resource_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('unique_bookmark', 'bookmarks', type_='unique')
    op.create_index(op.f('ix_bookmarks_url'), 'bookmarks', ['url'], unique=False)
    op.drop_constraint('bookmarks_user_id_fkey', 'bookmarks', type_='foreignkey')
    op.create_foreign_key(None, 'bookmarks', 'users', ['user_id'], ['id'])
    op.drop_column('bookmarks', 'resource_id')
    op.drop_column('bookmarks', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmarks', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('bookmarks', sa.Column('resource_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bookmarks', type_='foreignkey')
    op.create_foreign_key('bookmarks_user_id_fkey', 'bookmarks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_bookmarks_url'), table_name='bookmarks')
    op.create_unique_constraint('unique_bookmark', 'bookmarks', ['user_id', 'resource_id', 'resource_type'])
    op.alter_column('bookmarks', 'resource_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('bookmarks', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('bookmarks', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('bookmarks', 'url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
