"""Make url column non-nullable

Revision ID: eeb880dd58e1
Revises: 1739dfe43722
Create Date: 2025-03-15 16:25:00.106751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeb880dd58e1'
down_revision: Union[str, None] = '1739dfe43722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('community_uploads', 'url', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('community_uploads', 'url', nullable=True)

    # ### end Alembic commands ###
